### ISSUE TITLE
Duplicate Block

### ISSUE THREAD

**Issue by theskyfloor** [benjamminf/craft-neo#15]
It would be a great piece of functionality if it was possible to duplicate an existing and already built block when adding content... with all of the sub fields in tact (although they don't necessarily have to be filled out, for my use case at least)

**Comment by benjamminf** [comment]
I've got the basics down under the `feature/duplicate-block` branch. So far it seems to work fine with some of the native Craft fields. Yet to see what happens when duplicating blocks with Matrix and other third-party fields, but it's looking promising.

**Comment by theskyfloor** [comment]
I am testing it out! Where is the UI for duplicating a block? Or is there some other way to test it? I am happy to give it a whirl

**Comment by benjamminf** [comment]
Yeah it's a development branch so the Javascript needs building. I've attached the [compiled versions here](https://github.com/benjamminf/craft-neo/files/322538/Archive.zip) (just replace the `main.js` and `main.js.map` files in the `neo/resources/` directory), or if you run an `npm install` then `webpack` on the repository's root directory you can build it yourself.

I should point out the `feature/duplicate-block` branch also contains all the changes for the upcoming `1.2.2` release. This release [dramatically improves performance](https://github.com/benjamminf/craft-neo/issues/16), but it's still in a trial period just in case some bugs passed testing.

**Comment by benjamminf** [comment]
I've reworked my solution for duplicate blocks, and now it's essentially guaranteed to work with any field type. So look forward to this in `1.3.0` :+1:

**Comment by benjamminf** [comment]
Accidentally closed it... my bad.

**Comment by theskyfloor** [comment]
Cool! Want any testing? I tested the last version and definitely ran into some bugs... but figured you would find them too : )

**Comment by benjamminf** [comment]
I'd be happy for you to test :) [Here's a copy of the latest changes.](https://github.com/benjamminf/craft-neo/files/325796/neo.zip) I hadn't had a chance to really test the older version you were testing, but I could imagine it would've had quite a few bugs. The newer version renders the duplicated block server-side, instead of trying to rebuild one on the client (which no doubt would be problematic for certain fields). I'm happy for you to report any bugs you find here. Thanks for helping out!

**Comment by theskyfloor** [comment]
Nice it works much better and actually preserves data which it wasn't before!

The only bug I am noticing off the bat is that if I duplicate a top level block it is then moved into a child of the parent instead of creating another parent block - as a side effect of that behavior the sub blocks aren't being duplicated either.

![screen shot 2016-06-21 at 9 42 19 am](https://cloud.githubusercontent.com/assets/8887839/16233791/2a4ead34-3795-11e6-8103-b644e5e0cb82.png)

**Comment by benjamminf** [comment]
Ah yeah, that was a silly mistake. I've fixed it now. [Here are the updated JS files.](https://github.com/benjamminf/craft-neo/files/326848/Archive.zip)

**Comment by benjamminf** [comment]
Child blocks now duplicate with blocks. [Here's the updated compiled JS if you want to test it.](https://github.com/benjamminf/craft-neo/files/327955/resources.zip)

**Comment by theskyfloor** [comment]
Testing it now

**Comment by theskyfloor** [comment]
Great! Works much better than it had been. Still not duplicating in a specific circumstance - attached image because it gets confusing trying to verbally describe what is and isn't happening with all the child blocks... haha. Sorry if I am being annoying!

![screen shot 2016-06-22 at 10 08 56 am](https://cloud.githubusercontent.com/assets/8887839/16271983/af88f276-3861-11e6-9f0e-70fd4029a7e8.png)

**Comment by benjamminf** [comment]
Ah I see, so it's not working with Matrix fields. Seems a little strange... I'm looking into it. Thanks!
